# Generated by Django 3.0.7 on 2021-01-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minamount',
        ),
        migrations.RemoveField(
            model_name='productlang',
            name='detail',
        ),
    ]
