# Generated by Django 3.0.7 on 2021-01-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210111_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylang',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categorylang',
            name='keywords',
        ),
    ]
